services:
  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    restart: unless-stopped
    networks:
      - outside
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.domain.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=https"
      # set HSTS headers with middleware
      - "traefik.http.routers.whoami.middlewares=hsts-headers@file"
      # set TLS options
      - "traefik.http.routers.whoami.tls.options=modern@file"

# attach to the outside network
networks:
  outside:
    external: true
    name: traefik-outside-net
