services:
  traefik:
    image: traefik:banon
    container_name: traefik
    restart: unless-stopped
    networks:
      - outside
    command:
      # docker backend
      - "--providers.docker=true"
      # services are not exposed by default
      - "--providers.docker.exposedbydefault=false"
      # dynamic configuration folder
      - "--providers.file.directory=/dc"
      # enable HTTP entrypoint and redirect to HTTPS
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      # enable HTTPS entrypoint
      - "--entrypoints.https.address=:443"
      # enable TLS
      - "--entrypoints.https.http.tls=true"
      # Let's encrypt SSL certificate
      - "--entrypoints.https.http.tls.certresolver=le"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=name@domain.localhost"
      - "--certificatesresolvers.le.acme.storage=/le/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./dc:/dc"
      - "./le:/le"

# create a network to the outside for traefik
networks:
  outside:
    name: traefik-outside-net
