services:
  freshrss:
    image: freshrss/freshrss:edge
    container_name: freshrss
    restart: unless-stopped
    volumes:
      - "./data:/var/www/FreshRSS/data"
      - "./extensions:/var/www/FreshRSS/extensions"
    networks:
      - outside
    environment:
      - "CRON_MIN=*/20"
      - "TZ=UTC"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freshrss.rule=Host(`freshrss.domain.localhost`)"
      - "traefik.http.routers.freshrss.entrypoints=https"
      # set TLS options
      - "traefik.http.routers.freshrss.tls.certresolver=le"
      - "traefik.http.routers.freshrss.tls.options=modern@file"

# attach to the outside network
networks:
  outside:
    external: true
    name: traefik-outside-net
